### ISSUE TITLE
How to use Error Messages for requestWorker callback?

### ISSUE THREAD

**Issue by endze1t** [sirian/node-cluster-hub#7]
Hey.  Here is an example Code:

```js
const cluster = require('cluster');
const Hub = require('cluster-hub');
const hub = new Hub();

if (cluster.isMaster) {
    var worker = cluster.fork();

    hub.requestWorker(worker, 'myEvent', {
        link: 'https://something'
    }, (err, response) => {
        if (err) return console.log(err);
        console.log(response);
    });
} else {
    hub.on('myEvent', function (data, sender, callback) {
        // callback(null, {success: true, body: '<html></html>'});
        callback(new Error('TEST_ERROR'));
    });
}
```

The err is always only 

> {}

Is this a problem with Nodejs or this Libary?

**Comment by sirian** [comment]
Hi. Problem is inside serialization inside node. clean example

```
const cluster = require('cluster');

if (cluster.isMaster) {
     const worker = cluster.fork();
     worker.on('message', console.log);
} else {
    cluster.worker.send({error: new Error("TEST")});
}
```

They using JSON.stringify. so `JSON.stringify(new Error('test'))` is `{}`. You could easily patch this behavior by adding `toJSON` method to `Error.prototype`.


```
const cluster = require('cluster');
const Hub = require('cluster-hub');
const hub = new Hub();

Error.prototype.toJSON = function() {
    return {message: this.message};
}

if (cluster.isMaster) {
    var worker = cluster.fork();

    hub.requestWorker(worker, 'myEvent', {
        link: 'https://something'
    }, (err, response) => {
        if (err) return console.log(err);
        console.log(response);
    });
} else {
    hub.on('myEvent', function (data, sender, callback) {
        // callback(null, {success: true, body: '<html></html>'});
        callback(new Error('TEST_ERROR'));
    });
}
```

**Comment by endze1t** [comment]
Hey, thanks for you response. But before patching `Error.prototype`. I just could do `callback({message: 'TEST_ERROR'}, null)`?

So it's technically not possible to pass a real error without `JSON.stringify` to the master or worker?

**Comment by sirian** [comment]
Yes, it's impossible to pass real objects in node.js 

https://nodejs.org/api/process.html#process_process_send_message_sendhandle_options_callback

> The message goes through serialization and parsing. The resulting message might not be the same as what is originally sent.

**Comment by sirian** [comment]
>Hey, thanks for you response. But before patching `Error.prototype`. I just could do `callback({message: 'TEST_ERROR'}, null)`?


Yes, you could pass error as you wish. `callback({message: 'foo', code: 123, blablabla: '...'})` or even `callback('Oops, error')`. Second argument in this case is not required

Moreover you could use more arguments.  `callback(arg1, arg2, arg3, ...)`. It's up to you. But internal errors always will apply callback with error as first argument. For example `callback(new Error('Worker died'))`
